insert into event_list (id,active,name) values (1,true, 'Agenda entrevista B&S');
insert into event_list (id,active,name) values (2,true, 'Entrevista B&S grupal');
insert into event_list (id,active,name) values (3,true, 'Entrevista B&S');
insert into event_list (id,active,name) values (4,true, 'Entrevista técnica');
insert into event_list (id,active,name) values (5,true, 'Envio comercial');
insert into event_list (id,active,name) values (6,true, 'Reciclaje');
insert into event_list (id,active,name) values (7,true, 'Feedback comercial');
insert into event_list (id,active,name) values (8,true, 'Envío a cliente');
insert into event_list (id,active,name) values (9,true, 'Feedback cliente');
insert into event_list (id,active,name) values (10,true, 'Entrevista cliente');
insert into event_list (id,active,name) values (11,true, 'Envío propuesta');
insert into event_list (id,active,name) values (12,true, 'Respuesta Propuesta');
insert into event_list (id,active,name) values (13,true, 'Desiste candidato');
insert into event_list (id,active,name) values (14,true, 'Desiste cliente');

insert into answer (id, name) values (1, 'Pasa entrevista');
insert into answer (id, name) values (2, 'No se ajusta al perfíl');
insert into answer (id, name) values (3, 'Candidato no recomendable');
insert into answer (id, name) values (4, 'No cumple con seniority');
insert into answer (id, name) values (5, 'No se presentó');
insert into answer (id, name) values (6, 'Excede banda');
insert into answer (id, name) values (7, 'Entrevista agendada');
insert into answer (id, name) values (8, 'Rechaza propuesta');
insert into answer (id, name) values (9, 'Acepta propuesta');
insert into answer (id, name) values (10, 'Desinteresado proyecto');
insert into answer (id, name) values (11, 'Desinteresado propuesta');
insert into answer (id, name) values (12, 'Desinteresado G&L');
insert into answer (id, name) values (13, 'Desinteresado salario');
insert into answer (id, name) values (14, 'Desinteres/Sin respuesta');
insert into answer (id, name) values (15, 'Búsqueda cerrada');