insert into answer_by_options (id, name) values (1, 'Agenda entrevista B&S');
insert into answer_by_options (id, name) values (2, 'Entrevista B&S grupal');
insert into answer_by_options (id, name) values (3, 'Entrevista B&S');
insert into answer_by_options (id, name) values (4, 'Entrevista técnica');
insert into answer_by_options (id, name) values (5, 'Envio comercial');
insert into answer_by_options (id, name) values (6, 'Reciclaje');
insert into answer_by_options (id, name) values (7, 'Feedback comercial');
insert into answer_by_options (id, name) values (8, 'Envío a cliente');
insert into answer_by_options (id, name) values (9, 'Feedback cliente');
insert into answer_by_options (id, name) values (10, 'Entrevista cliente');
insert into answer_by_options (id, name) values (11, 'Envío propuesta');
insert into answer_by_options (id, name) values (12, 'Respuesta Propuesta');
insert into answer_by_options (id, name) values (13, 'Desiste candidato');
insert into answer_by_options (id, name) values (14, 'Desiste cliente');

insert into answer (id, name) values (1, 'Pasa entrevista');
insert into answer (id, name) values (2, 'No se ajusta al perfíl');
insert into answer (id, name) values (3, 'Candidato no recomendable');
insert into answer (id, name) values (4, 'No cumple con seniority');
insert into answer (id, name) values (5, 'No se presentó');
insert into answer (id, name) values (6, 'Excede banda');
insert into answer (id, name) values (7, 'Entrevista agendada');
insert into answer (id, name) values (8, 'Rechaza propuesta');
insert into answer (id, name) values (9, 'Acepta propuesta');
insert into answer (id, name) values (10, 'Desinteresado proyecto');
insert into answer (id, name) values (11, 'Desinteresado propuesta');
insert into answer (id, name) values (12, 'Desinteresado G&L');
insert into answer (id, name) values (13, 'Desinteresado salario');
insert into answer (id, name) values (14, 'Desinteres/Sin respuesta');
insert into answer (id, name) values (15, 'Búsqueda cerrada');